FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir uv

COPY ia-judge/requirements.txt ./requirements.txt
RUN uv pip install --system --no-cache -r requirements.txt

COPY ./ia-judge /app/ia-judge

WORKDIR /app/ia-judge

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
