from typing import List, Literal, Optional
from pydantic import BaseModel, Field


class SearchStringJudgeRequest(BaseModel):
    topic: str = Field(..., description="The topic of the systematic review")
    search_string: str = Field(..., description="The search string generated by another model")
    database: Optional[str] = Field("Scopus", description="Target database, e.g., Scopus, IEEE, ACM, Web of Science")


class ArticleClassification(BaseModel):
    title: str
    abstract: Optional[str] = None
    model_classification: str = Field(..., description="Classification made by another model, e.g., INCLUDE, EXCLUDE, MAYBE")
    model_justification: Optional[str] = None


class ArticleClassificationJudgeRequest(BaseModel):
    review_objective: str
    inclusion_criteria: Optional[str] = None
    exclusion_criteria: Optional[str] = None
    articles: List[ArticleClassification]


class SearchCriterionResult(BaseModel):
    score: float = Field(..., ge=0, le=5)
    justification: str = ""


class SearchStringJudgeCriteria(BaseModel):
    conceptual_coverage: SearchCriterionResult
    synonym_quality: SearchCriterionResult
    boolean_operators: SearchCriterionResult
    database_compatibility: SearchCriterionResult
    recall_potential: SearchCriterionResult
    precision: SearchCriterionResult


class SearchStringJudgeResponse(BaseModel):
    type: Literal["SEARCH_STRING_JUDGE"] = "SEARCH_STRING_JUDGE"
    final_score: float = Field(..., ge=0, le=5)
    decision: Literal["APPROVE", "REVISE", "REJECT"]
    criteria: SearchStringJudgeCriteria
    identified_problems: List[str] = Field(default_factory=list)
    improvement_suggestions: List[str] = Field(default_factory=list)


class ArticleJudgeResult(BaseModel):
    title: str
    model_classification: str
    judge_verdict: Literal["CORRECT", "UNCERTAIN", "INCORRECT"]
    confidence_score: float = Field(..., ge=0, le=5)
    judge_justification: str = ""
    human_review_recommended: bool = True


class ArticleClassificationJudgeResponse(BaseModel):
    type: Literal["ARTICLE_CLASSIFICATION_JUDGE"] = "ARTICLE_CLASSIFICATION_JUDGE"
    overall_result: Literal["APPROVE", "REVISE", "REJECT"]
    articles: List[ArticleJudgeResult]
    summary: str = ""
    main_risks: List[str] = Field(default_factory=list)
